spring.application.name=Food_Service
spring.datasource.url=jdbc:mariadb://172.16.40.219:3306/food_order_system
spring.datasource.username=labuser
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

server.port=8082
server.address=0.0.0.0