spring.application.name=Data_partition_horizontal
spring.datasource.url=jdbc:mariadb://localhost:3306/ktmt5
spring.datasource.username=root
spring.datasource.password=truc2004

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect