version: "3.9"

services:

  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - --api.insecure=true       # dashboard traefik
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"               # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./acme.json:/acme.json
    networks:
      - web

  flask:
    build: ./app/flask_app
    container_name: flask-app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flask.rule=Host(`flask.localhost`)"
      - "traefik.http.routers.flask.entrypoints=web"
    networks:
      - web

networks:
  web:
    external: false