events {}

http {
    upstream flask_app {
        server flask1:5000;
        server flask2:5000;
    }

    server {
        listen 8080;

        location / {
            proxy_pass http://flask_app;
        }
    }
}