services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./db_data:/data/db
    networks:
      - app_network

  nodeapp:
    build: ./app
    container_name: node_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge