services:
  app1:
    image: nginx:alpine
    container_name: app1
    networks:
      - mynetwork

  app2:
    image: busybox
    container_name: app2
    command: sleep 3600
    networks:
      - mynetwork

networks:
  mynetwork: